name: Set up Javascript
description: Installs Node.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '16.14.2'
        cache: 'yarn'
    - name: Install yarn dependencies
      shell: bash
      run: yarn install --frozen-lockfile
